MongoHandler:
  numWorkers: 7
  dbHost: localhost
  dbPort: 27017
  dbUser: admin
  dbPassword: admin

IngestionGrpcServer:
  port: 50051

IngestionPerformanceBenchmark:
  grpcConnectString: "localhost:50051"
  startSeconds: 1698767462

QueryGrpcServer:
  port: 50052

QueryPerformanceBenchmark:
  grpcConnectString: "localhost:50052"
  startSeconds: 1698767462
