# MongoClient: Settings for connection to MongoDB.
MongoClient:

  # MongoClient.dbHost: The host that is running the MongoDB server.
  # Default value is "localhost", specifying that the database is running on the same host as the Data Platform services.
  dbHost: localhost

  # MongoClient.dbPort: Network port on dbHost for the MongoDB service.  MongoDB default installation is 27017.
  dbPort: 27017

  # MongoClient.dbUser: Username for connection to MongoDB by Data Platform services.
  dbUser: admin

  # MongoClient.dbPassword: Password for dbUser for connection to MongoDB by Data Platform services.
  dbPassword: admin

# IngestionServer: Settings for the Ingestion server process.
IngestionServer:

  # IngestionServer.port: Network port for Ingestion Service gRPC.
  port: 50051

# IngestionHandler: Settings for the Ingestion Service request handler.
IngestionHandler:

  # IngestionHandler.numWorkers: Number of worker threads used by the Ingestion Service request handler.
  # This parameter might take some tuning on deployments to get the best performance.
  numWorkers: 7

# IngestionBenchmark: Settings for the Ingestion Service performance benchmark application.
IngestionBenchmark:

  # IngestionBenchmark.grpcConnectString: String used for gRPC connection to Ingestion Service including "host:port".
  grpcConnectString: "localhost:50051"

  # IngestionBenchmark.startSeconds: Specifies fixed start time for data created by Ingestion benchmark application.
  startSeconds: 1698767462

# QueryServer: Settings for the Query server process.
QueryServer:

  # QueryServer.port: Network port for Query Service gRPC.
  port: 50052

# QueryHandler: Settings for the Query Service request handler.
QueryHandler:

  # QueryHandler.numWorkers: Number of worker threads used by the Query Service request handler.
  # This parameter might take some tuning on deployments to get the best performance.
  numWorkers: 7

# QueryBenchmark: Settings for the Query Service performance benchmark applications.
QueryBenchmark:

  # QueryBenchmark.grpcConnectString: String used for gRPC connection to Query Service including "host:port".
  grpcConnectString: "localhost:50052"

# annotationServer: Settings for the annotation server process.
annotationServer:

  # annotationServer.port: Network port for Annotation Service gRPC.
  port: 50053

# annotationHandler: Settings for the annotation Service request handler.
annotationHandler:

  # annotationHandler.numWorkers: Number of worker threads used by the annotation Service request handler.
  # This parameter might take some tuning on deployments to get the best performance.
  numWorkers: 7
